services:
  api-hotel:
    container_name: api-hotel
    build:
      context: .
    image: api-hotel
    ports:
      - "5000:5000"
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - REDIS_URL=${REDIS_URL}
    networks:
      - hotels
    depends_on:
      - hotel-db

  hotel-db:
    container_name: hotel_db
    restart: always
    image: postgres:14.6
    ports:
      - "5433:5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - hotels

networks:
  hotels:
    driver: bridge
